
build-backend = "setuptools.build_meta"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.7.0",
]

[tool.cibuildwheel]
before-all = [

    "sudo apt-get install gpiod libgpiod-dev libgpiod-doc"

]

