name: Build Status
on: ["push"]

jobs:
  build:
    name: buildcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v1
      with:
        commands: |
            sudo apt-get update
            sudo apt-get install python3-gpiozero python3-config
            sudo apt-get install git-all
            sudo ./install-deps.sh
            make
