name: Build Status
on: ["push"]

jobs:
  build:
    name: buildcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v1
      with:
        image_additional_mb: 10000
        commands: |
            sudo apt-get update -y
            sudo apt-get full-upgrade -y
            sudo apt-get install git-all -y
            sudo apt install swig python-dev python3-dev -y
            sudo apt install python-setuptools python3-setuptools -y
            sudo ./install-deps.sh
            make
