name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - name: Clone lgpio
        uses: actions/checkout@v2
        with:
          repository: 'joan2937/lg'
          ref: '9ebaf583b8647d5531a6d2d797cb27d4aefb6d1a'

      - name: Build and Install lgpio
        run: |
          make
          sudo make install
          sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
          sudo ldconfig
          sudo chown -R $USER:$USER /home/runner/work

      - name: Clone hx711
        uses: actions/checkout@v2
        with:
          repository: 'endail/hx711'

      - name: Build and install libhx711
        run: |
          make
          sudo make install
          sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
          sudo ldconfig
          sudo chown -R $USER:$USER /home/runner/work


      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl