name: Build Status
on: ["push"]

jobs:
  build:
    name: buildcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install deps
        run: sudo ./install-deps

      - name: Build
        run: make
