name: Upload to PyPI
on: ["push"]

jobs:

  build:

    name: Build on ${{ matrix.cpu }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: ["raspios_lite:2021-05-07"]
        cpu: [arm1176, cortex-a8]

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Build RPI environment
      uses: pguyot/arm-runner-action@v1
      with:
        commands: ./gh-actions-rpi-cmd.sh
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 10000
        cpu: ${{ matrix.cpu }}
        optimize_image: false
        copy_artifact_path: dist/
        copy_artifact_dest: .

    - name: Publish distribution 📦 to PyPI
      if: ${{ success() }} && startsWith(github.ref, 'refs/tags') }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
        verbose: true

    - name: Finish
      if: ${{ always() }}
      run: echo done
